version: 2
jobs:
  build:
    machine: true
    environment:
      RUNUSER: python
      SUBMODULE_BRANCH: develop
    steps:
      - checkout
      - run: |
          make build
          make test
          make lint
workflows:
  version: 2
  workflow:
    jobs:
      - build